### ISSUE TITLE
Error 1046: No database selected

### ISSUE THREAD

**Issue by caijinlin** [rubenv/sql-migrate#116]
```
development:
    dialect: mysql
    datasource: root@/tesrt?parseTime=true
    dir: migrations/mysql
    table: migrations
```

this is my dbconfig.yml, but it show 'No database selected' when I run command 'sql-migrate status
