### ISSUE TITLE
Could not parse config: No environment: development

### ISSUE THREAD

**Issue by martin-flower** [rubenv/sql-migrate#123]
I don't understand why I get the following error - is go caching or ignoring the environment variable?

```
host:dbMigrations martin$ sql-migrate up -env=localdocker
Applied 25 migrations
host:dbMigrations martin$ sql-migrate down 1 -env=localdocker
Could not parse config: No environment: development
```
`dbconfig.yml`:

```
localdocker:
    dialect: postgres
    datasource: dbname=postgres port=5432 user=routesroot sslmode=disable
    dir: migrations
````

If I rename `localdocker`to `development` everything works .. ..
