### ISSUE TITLE
how to configure LineSeparator?

### ISSUE THREAD

**Issue by opensas** [rubenv/sql-migrate#135]
I'm using mssql and I'm trying to use `GO` as line separator as stated [here](https://github.com/rubenv/sql-migrate#writing-migrations)

this is what I tried so far in my dbconf.yml

```yaml
development:
  dialect: mssql
  datasource: sqlserver://sa:xxxxxx@server
  dir: migrations
  table: migrations
  sqlparse.LineSeparator: GO
  LineSeparator: GO
  lineseparator: GO
  sqlparse.lineseparator: GO
```

it doesn't seem to take the configuration, and when I try to run a migration that contains GO I get:

```shell
$ sql-migrate.exe up
Migration failed: mssql: Incorrect syntax near 'GO'. handling 0001-table_test.sql
```

this is the migration

```sql
-- +migrate Up
CREATE TABLE [dbo].[Test](
	[id] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[name] [varchar](500) NULL,
	[surname] [varchar](500) NULL,
 CONSTRAINT [PK_Test] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
;

-- +migrate Down
DROP TABLE [dbo].[Test]
GO
;
```
