### ISSUE TITLE
strong password in dbconfig.yml not escaping

### ISSUE THREAD

**Issue by mdere-unbound** [rubenv/sql-migrate#139]
For some reason in the following

```
development:
    dialect: postgres
    datasource: dbname=local user=admin password="......" host=localhost port=5432 sslmode=disable
    dir: migrations/postgres
```

When I use a complicated strong password with symbols, this gives me auth errors, but as soon I turn the password to something simple - it goes through.

Am I missing something?
