### ISSUE TITLE
Migration failed: pq: relation "gorp_migrations" does not exist

### ISSUE THREAD

**Issue by mdere-unbound** [rubenv/sql-migrate#151]
Any reason why this could be happening? I checked my permissions for the user to access the DB and it looks good to me...what else can I be missing? Also it does seem like the sql-migrate up command too is creating the gorp_migrations table too.

**Comment by artn** [comment]
Same issue.
Though sql-migrate creates table for migrations, migration failed with message
`Migration failed: pq: relation "migrations" does not exist handling 000_db_schema.sql`

**Comment by kkyr** [comment]
I had the same issue and fixed it by providing a `schema` inside `dbconfig.yaml`:

```
development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=test user=user password=pass sslmode=disable
  dir: migrations
  schema: account
  table: migrations 
```
