### ISSUE TITLE
sql-migrate up returns: Migration failed: Error 1146: Table 'go_test.user' doesn't exist handling 20210114023524-create_user_table.sql

### ISSUE THREAD

**Issue by 1200mhz** [rubenv/sql-migrate#220]
I have a migration in the path: migrations/mysql/20210114023525-create_user_table.sql
```
-- +migrate Up
CREATE TABLE IF NOT EXISTS User1
(
    id         INT AUTO_INCREMENT     NOT NULL,
...
```
dbconfig.yml:
```
development:
  dialect: mysql
  datasource: gotest:gotest@tcp(db:3306)/go_test?parseTime=true
  table: migrations
  dir: migrations/mysql
```

The library sees it, but writes "doesn't exist handling"
Whats it meens??
