### ISSUE TITLE
IgnoreUnknown is not working

### ISSUE THREAD

**Issue by rohitjha941** [rubenv/sql-migrate#225]
I have this configuration and am trying to set ignore unknown as true 

```
development:
  dialect: postgres
  datasource: <>
  sslmode=disable
  dir: migrations
  table: migrations
  ignoreunknown: true
```

Even after setting this, It is giving me err ` unknown migration in database`
