### ISSUE TITLE
schema.table in table setting

### ISSUE THREAD

**Issue by rkintzi** [rubenv/sql-migrate#38]
Would be nice, if I could put table with migrations in schema other than default (`public` in PostgreSQL):
```
production:
    dialect: postgres
    table: someschema.migrations
    ...
 ```

**Comment by ndrewnee** [comment]
@rkintzi You can already use it. Just write in dbconfig.yml
```
production:
    dialect: postgres
    table: migrations
    schema: another_schema
    ...
```
