### ISSUE TITLE
Offer possibility to use sql-migrate cli with env vars instead of file conf

### ISSUE THREAD

**Issue by jdelobel** [rubenv/sql-migrate#82]
Is it possible to to use sql-migrate cli with env vars instead of file conf?

**Comment by paulwalker** [comment]
It seems a bit strange that the migrations can be accessed via bindata, but then a config file is still required?

**Comment by rubenv** [comment]
@paulwalker please open a different issue when asking a different question.

**Comment by sbrudz** [comment]
I was able to use environment variables within the dbconfig.yml file:
```yml
development:
    dialect: mysql
    datasource: ${DBUSER}:${DBPASS}@tcp(${DBHOST}:${DBPORT})/${DBNAME}?parseTime=true
    dir: migrations
    table: migrations
```
